/**
 * words.js — Wordle Battle Word Bank
 * WORD_LIST: common 5-letter words used as answers
 * VALID_GUESSES: extended set accepted as valid guesses
 */

const WORD_LIST = [
  "about","above","abuse","actor","acute","admit","adopt","adult","after","again",
  "agent","agree","ahead","alarm","album","alert","alike","align","alive","alley",
  "allot","allow","alone","along","alter","angel","anger","angle","angry","anime",
  "annex","apart","apple","apply","arena","argue","arise","armor","aroma","arose",
  "array","arrow","aside","asked","asset","atlas","attic","audit","avoid","award",
  "aware","awful","badly","basic","basis","batch","beach","beard","beast","began",
  "being","below","bench","berry","birth","black","blade","blame","bland","blank",
  "blast","blaze","bleed","blend","bless","blind","block","blood","bloom","blown",
  "board","bonus","boost","bound","brain","brand","brave","bread","break","breed",
  "brick","bride","brief","bring","broad","brook","brown","brush","buddy","build",
  "built","burst","buyer","cabin","cache","camel","candy","cargo","carry","catch",
  "cause","cease","chain","chair","chaos","charm","chart","chase","check","cheek",
  "chess","chest","chief","child","china","choir","chose","chunk","civic","civil",
  "claim","clamp","clang","clash","class","clean","clear","clerk","click","cliff",
  "climb","cling","clock","clone","close","cloth","cloud","clown","coach","coast",
  "cobra","color","combo","comic","comma","coral","could","count","court","cover",
  "craft","crane","crash","crazy","cream","creek","crime","crisp","cross","crowd",
  "cruel","crush","curve","cycle","daily","dance","datum","death","debut","decay",
  "decor","delay","delta","depot","depth","derby","devil","digit","disco","ditch",
  "dizzy","dodge","doing","donor","doubt","dough","dowry","draft","drain","drama",
  "drank","drawn","dream","dried","drink","drive","drone","drove","druid","drunk",
  "dryer","dutch","dying","eagle","early","earth","eight","elite","email","ember",
  "empty","enemy","enjoy","enter","entry","equal","error","essay","event","every",
  "exact","excel","exist","extra","fable","faint","fairy","faith","false","fancy",
  "fangs","fatal","fault","feast","fetch","fever","fiber","field","fifth","fifty",
  "fight","final","first","fixed","flake","flame","flash","flask","fleet","flesh",
  "float","flood","floor","flour","fluid","flute","focal","focus","force","forge",
  "forth","forum","found","frame","fresh","front","frost","froze","fruit","fully",
  "funny","fuzzy","gamma","ghost","giant","given","gland","glass","glide","globe",
  "gloom","gloss","glove","going","grace","grade","grain","grand","grant","graph",
  "grasp","grass","grave","great","green","greet","grief","grill","grind","groan",
  "groin","gross","group","grove","grown","gruel","guess","guest","guide","guild",
  "guile","guise","gusto","habit","happy","harsh","haven","heart","heavy","hedge",
  "hello","hence","herbs","hinge","hippo","hiked","hoist","honor","horse","hotel",
  "house","human","humid","hurry","hyena","hyper","ideal","image","imply","inbox",
  "indie","inner","input","inter","intro","inure","irony","issue","ivory","japan",
  "joker","joint","judge","juice","juicy","jumbo","jumpy","karma","kayak","kebab",
  "knack","kneel","knife","knock","known","label","lance","large","laser","later",
  "laugh","layer","learn","lease","leave","legal","lemon","level","light","limit",
  "liver","local","lodge","logic","loose","lotus","lousy","lower","lucky","lunar",
  "lying","magic","major","maker","manor","maple","march","match","media","merit",
  "metal","meter","might","minor","minus","model","money","month","moral","motor",
  "motto","mound","mount","mouse","mouth","moved","movie","muddy","music","nasal",
  "naval","needy","nerve","never","night","ninja","noble","noise","north","noted",
  "novel","nurse","nymph","occur","ocean","offer","often","olive","onset","opera",
  "orbit","order","organ","other","outdo","outer","owned","oxide","ozone","paced",
  "paint","panic","paper","party","pasta","patch","pause","peace","peach","pearl",
  "pedal","penny","perch","peril","phase","phone","photo","pilot","pinch","pixel",
  "pizza","place","plain","plane","plant","plate","plaza","plead","pluck","plumb",
  "plume","plump","plunge","plunk","point","polar","poppy","porch","power","press",
  "price","pride","prime","print","prior","prize","probe","prone","proof","prose",
  "proud","prove","proxy","pubic","pulpy","punch","pupil","purse","queen","query",
  "queue","quick","quiet","quota","quote","rabbi","radar","radio","raise","rally",
  "ranch","range","rapid","ratio","reach","react","realm","rebel","refer","reign",
  "relax","repay","rider","rifle","right","rigid","risky","rival","river","roast",
  "robot","rocky","rogue","roman","rough","round","route","rugby","ruler","runic",
  "rural","rusty","sadly","saint","salsa","sauce","scale","scare","scene","scent",
  "scone","scope","score","scout","screw","seize","sense","serve","seven","shall",
  "shame","shape","share","shark","sharp","sheep","shelf","shell","shift","shine",
  "shirt","shock","shore","short","shout","shown","siege","sigma","silly","since",
  "sixth","sixty","skill","skull","sky","slate","sleep","slice","slide","slope",
  "smart","smell","smelt","smile","smoke","solid","solve","sorry","south","space",
  "spark","speak","spear","speed","spend","spice","spill","spine","spite","split",
  "spoke","spore","sport","spray","squad","stack","stage","stain","stake","stale",
  "stall","stand","stark","start","state","stays","steel","steep","steer","stern",
  "still","stock","stomp","stone","stood","storm","story","stove","straw","strip",
  "stuck","study","stuff","style","sugar","suite","super","surge","swamp","swear",
  "sweep","sweet","swept","swift","sword","swore","table","taken","taste","teach",
  "tears","teeth","tempo","tense","tenth","terms","thank","theme","there","these",
  "thick","thing","think","those","three","threw","throw","tiger","tight","timer",
  "tired","title","today","token","tooth","topic","total","touch","tough","towel",
  "tower","toxic","track","trade","trail","train","trait","trawl","tread","treat",
  "trend","trial","tribe","trick","tried","trill","trite","troop","truck","truly",
  "trunk","trust","truth","tummy","tuner","tunic","twist","tying","ultra","uncle",
  "under","unify","union","unite","unity","until","unzip","upper","urban","usage",
  "usual","utter","valid","value","valve","vapor","vault","video","vigor","viral",
  "virus","visit","visor","vista","vital","vivid","voice","voter","wagon","waste",
  "watch","water","weary","weave","wedge","weird","whale","wheat","where","which",
  "while","white","whose","widen","witch","woman","women","world","worry","worse",
  "worst","worth","would","wound","wrath","write","wrote","yacht","yield","young",
  "youth","zebra","zonal",
];

// Extended valid guess set (union of WORD_LIST + extra common words)
const EXTRA_VALID = [
  "aahed","aalii","abaci","aback","abase","abash","abate","abbey","abbot","abhor",
  "abide","abler","abode","aboon","abore","abash","acorn","adage","adorn","aegis",
  "affix","afoot","afoul","agave","aglow","agony","agora","agile","aider","aisle",
  "algae","alias","aloft","amass","amaze","amble","amend","amid","amino","amiss",
  "amity","among","ample","amuse","ankle","annoy","antic","anvil","aphid","aptly",
  "ardor","ardent","argot","array","atone","atop","atria","attic","audio","augur",
  "avail","avow","axial","axiom","azure","badge","bagel","baste","baton","bayou",
  "bazaar","beady","beige","bevel","birch","bitty","blimp","blithe","bloat","bloke",
  "booze","bossy","botch","bough","brace","brash","brawn","brisk","broil","brood",
  "broom","broth","brunt","cacao","cadet","cairn","caper","capon","carve","cedar",
  "chafe","chaff","chant","chasm","chive","chord","chore","chuck","chump","churn",
  "cinch","cleat","cleave","cleft","clerk","cling","clink","clomp","clout","coax",
  "cobalt","codex","comet","comfy","connote","crone","croon","crude","crust","crypt",
  "daisy","dally","datum","daunt","dawdle","delta","dense","depot","derby","deter",
  "divan","dodge","dogma","dowel","downy","drape","drawl","dregs","drool","droop",
  "dudgeon","duvet","dwell","easel","edict","egret","elbow","elope","elute","embed",
  "emote","erupt","evade","evoke","exert","exile","exude","fable","facet","flank",
  "flare","flown","fluff","flunk","flurry","glean","gloat","gloss","gorge","gouge",
  "graze","gripe","gruel","guava","guile","gulch","gully","gusto","gutter","haste",
  "hatch","heave","herald","horde","homer","homer","hound","hover","hunch","hutch",
  "igloo","impel","infer","ingot","inlay","inlet","ivory","joust","knave","knelt",
  "laden","ladle","larva","latch","latte","leapt","ledge","lemma","levee","liver",
  "llama","loathe","lobby","lofty","logic","lyric","mantle","maple","marsh","maxim",
  "moose","moult","mural","murky","musty","myrrh","naive","navel","notch","nuance",
  "oaken","occur","omega","onion","onset","ooze","optic","ovoid","pagan","papal",
  "parry","paste","patio","paved","pebble","peddle","peeve","pique","pixel","plait",
  "plank","plush","poach","podium","poise","polyp","preen","prism","privy","psalm",
  "puffy","pug","quirk","quota","radon","raven","raven","rebus","relic","repel",
  "resin","retch","revel","rhyme","ridge","rigor","rodeo","roomy","rupee","rustle",
  "salve","salvo","savvy","scald","scalp","scaly","scamp","scram","scrod","shawl",
  "sheen","sheer","shone","shrub","shrug","shuck","shunt","sigma","simmer","sinew",
  "siren","sixth","skew","skimp","siren","slack","slain","slang","slap","sleet",
  "sleek","slew","slick","slimy","slink","sloth","slump","slunk","smirk","smite",
  "smock","snare","snide","snore","snort","snout","snuff","soggy","solvent","soothe",
  "spawn","speck","spew","spiel","spiky","spire","spoof","spoon","spout","sprig",
  "spunk","spurn","staid","stoic","stoop","strife","stung","stunk","swipe","swirl",
  "syrup","talon","taunt","tawny","thane","thatch","thorn","throe","throb","throng",
  "thud","thump","tiara","tithe","topple","torso","totem","truce","trump","tuber",
  "twerp","twirl","udder","ulcer","uncut","unfed","unfit","unify","unmet","unruly",
  "unwed","vaunt","venom","verge","vigor","viper","vitae","vogue","voila","vouch",
  "waft","waltz","wander","warty","waver","whelp","whiff","whirl","windy","witty",
  "wizen","wreak","wrest","wring","yearn","zesty","zilch","zippy",
];

const VALID_GUESSES = new Set([...WORD_LIST, ...EXTRA_VALID]);

function getRandomWord() {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)].toUpperCase();
}

function isValidWord(word) {
  return VALID_GUESSES.has(word.toLowerCase());
}

module.exports = { WORD_LIST, getRandomWord, isValidWord };
